# Generated by scripts/release/homebrew.sh for v0.2.0. Do not edit by hand.
cask "godterm" do
  version "0.2.0"
  sha256 "3903408af3e14227f95659ada4d4a8253ec2096ab4f4108674de88cd926378f1"

  url "https://github.com/daniel-farina/godterm/releases/download/v0.2.0/GodTerm-0.2.0-macos-universal.dmg"
  name "GodTerm"
  desc "Run many Claude Code sessions side by side, each on its own account"
  homepage "https://github.com/daniel-farina/godterm"

  container type: :dmg
  depends_on macos: :monterey
  conflicts_with formula: "godterm"

  app "GodTerm.app"
  binary "#{appdir}/GodTerm.app/Contents/MacOS/godterm"

  zap trash: [
    "~/.godterm",
  ]

  caveats <<~TEXT
    GodTerm runs Claude Code: install it too (npm install -g @anthropic-ai/claude-code).
  TEXT
end
