# Generated by scripts/release/homebrew.sh for v0.2.4. Do not edit by hand.
cask "godterm" do
  version "0.2.4"
  sha256 "9bdcdb1007ab232920e3393650951bba6eb0d11a202084777327ef1006e77939"

  url "https://github.com/daniel-farina/godterm/releases/download/v0.2.4/GodTerm-0.2.4-macos-universal.dmg"
  name "GodTerm"
  desc "Run many Claude Code sessions side by side, each on its own account"
  homepage "https://github.com/daniel-farina/godterm"

  depends_on macos: :monterey
  container type: :dmg

  app "GodTerm.app"
  binary "#{appdir}/GodTerm.app/Contents/MacOS/godterm"

  zap trash: "~/.godterm"

  caveats <<~TEXT
    GodTerm runs Claude Code: install it too (npm install -g @anthropic-ai/claude-code).
  TEXT
end
