# Generated by scripts/release/homebrew.sh for v0.2.6. Do not edit by hand.
cask "godterm" do
  version "0.2.6"
  sha256 "ed58235a9a8606cbf14294ffd557fdb009daf13b639fda0832312f95755cae0d"

  url "https://github.com/daniel-farina/godterm/releases/download/v0.2.6/GodTerm-0.2.6-macos-universal.dmg"
  name "GodTerm"
  desc "Run many Claude Code sessions side by side, each on its own account"
  homepage "https://github.com/daniel-farina/godterm"

  depends_on macos: :monterey
  container type: :dmg

  app "GodTerm.app"
  binary "#{appdir}/GodTerm.app/Contents/MacOS/godterm"

  zap trash: "~/.godterm"

  caveats <<~TEXT
    Voice and setup: run godterm and open Settings > Setup, or say "install the voice pack".
    Setup also installs Claude Code if it is missing.
  TEXT
end
