# Generated by scripts/release/homebrew.sh for v0.2.0. Do not edit by hand.
class Godterm < Formula
  desc "Run many Claude Code sessions side by side, each on its own account"
  homepage "https://github.com/daniel-farina/godterm"
  version "0.2.0"
  license "MIT"

  on_macos do
    url "https://github.com/daniel-farina/godterm/releases/download/v0.2.0/godterm-0.2.0-macos-universal.zip"
    sha256 "4f474cb0c5c2345f7f90acb831295dad6e2fb89dffae45f73ac71050c6c0e8d4"
  end

  on_linux do
    on_intel do
      url "https://github.com/daniel-farina/godterm/releases/download/v0.2.0/godterm-0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "2c82a0dd15ff708a49119c2a2e1258160f7768de8528445d93e0bd6527881191"
    end
    on_arm do
      url "https://github.com/daniel-farina/godterm/releases/download/v0.2.0/godterm-0.2.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "3832a8ede43917588cdcc3fb8319a7e9efd3ad50cd1e5211ac2783c649172bf9"
    end
    depends_on "alsa-lib"
  end

  def install
    # godterm finds godterm-speech next to its real path, so both live in
    # libexec and bin gets a link.
    libexec.install "godterm"
    libexec.install "godterm-speech" if File.exist?("godterm-speech")
    bin.install_symlink libexec/"godterm"
  end

  def caveats
    <<~TEXT
      GodTerm runs Claude Code: install it too (npm install -g @anthropic-ai/claude-code).
      Voice is optional: brew install ffmpeg whisper-cpp, then run godterm doctor.
    TEXT
  end

  test do
    assert_match version.to_s.split("-").first, shell_output("#{bin}/godterm --version")
  end
end
