# Generated by scripts/release/homebrew.sh for v0.2.5. Do not edit by hand.
class Godterm < Formula
  desc "Run many Claude Code sessions side by side, each on its own account"
  homepage "https://github.com/daniel-farina/godterm"
  version "0.2.5"
  license "MIT"

  on_macos do
    url "https://github.com/daniel-farina/godterm/releases/download/v0.2.5/godterm-0.2.5-macos-universal.zip"
    sha256 "8d7c02ebd60ab45026a85665ab1435bbfad93a331070ab6048fbba6ef4e98899"
  end

  on_linux do
    on_intel do
      url "https://github.com/daniel-farina/godterm/releases/download/v0.2.5/godterm-0.2.5-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "583335ec80abeb3f568051cb675c28482fba51476bbd630c22c11f68127117a2"
    end
    on_arm do
      url "https://github.com/daniel-farina/godterm/releases/download/v0.2.5/godterm-0.2.5-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "a38be67417e19aeb08fd03a1d61a8c35d4b1b104abbd1874c2720077f91d637e"
    end
    depends_on "alsa-lib"
  end

  def install
    # godterm finds godterm-speech next to its real path, so both live in
    # libexec and bin gets a link.
    libexec.install "godterm"
    libexec.install "godterm-speech" if File.exist?("godterm-speech")
    bin.install_symlink libexec/"godterm"
  end

  def caveats
    <<~TEXT
      Voice and setup: run godterm and open Settings > Setup, or say "install the voice pack".
      Setup also installs Claude Code if it is missing.
    TEXT
  end

  test do
    assert_match version.to_s.split("-").first, shell_output("#{bin}/godterm --version")
  end
end
