# Generated by scripts/release/homebrew.sh for v0.2.4. Do not edit by hand.
class Godterm < Formula
  desc "Run many Claude Code sessions side by side, each on its own account"
  homepage "https://github.com/daniel-farina/godterm"
  version "0.2.4"
  license "MIT"

  on_macos do
    url "https://github.com/daniel-farina/godterm/releases/download/v0.2.4/godterm-0.2.4-macos-universal.zip"
    sha256 "6cf7fdc2649ac0716e9e4aa8062b586f2102e5d8a8910f77687b5677fb9baba6"
  end

  on_linux do
    on_intel do
      url "https://github.com/daniel-farina/godterm/releases/download/v0.2.4/godterm-0.2.4-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "c4af2dc5c7b23cd47279c908b278dd7a3c291692e914c05f985efd33d75f075a"
    end
    on_arm do
      url "https://github.com/daniel-farina/godterm/releases/download/v0.2.4/godterm-0.2.4-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "a85d2fe3361c40d7cc4fdd3468fb7fd538f62b0671224f90997b5c0ae13e15bb"
    end
    depends_on "alsa-lib"
  end

  def install
    # godterm finds godterm-speech next to its real path, so both live in
    # libexec and bin gets a link.
    libexec.install "godterm"
    libexec.install "godterm-speech" if File.exist?("godterm-speech")
    bin.install_symlink libexec/"godterm"
  end

  def caveats
    <<~TEXT
      GodTerm runs Claude Code: install it too (npm install -g @anthropic-ai/claude-code).
      Voice is optional: brew install ffmpeg whisper-cpp, then run godterm doctor.
    TEXT
  end

  test do
    assert_match version.to_s.split("-").first, shell_output("#{bin}/godterm --version")
  end
end
